version: 0.0
os: linux

files:
  # Deploy WAR to Tomcat webapps
  - source: target/myapp.war
    destination: /opt/tomcat/webapps/

permissions:
  # Set wide-open permissions for Tomcat and deployed WAR
  - object: /opt/tomcat
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777

  # Scripts folder full access
  - object: scripts/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: scripts/health_check.sh
      timeout: 300
      runas: ec2-user
