version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17   # or corretto11 depending on requirement
  pre_build:
    commands:
      - echo "Cleaning previous build..."
      - mvn clean
  build:
    commands:
      - echo "Packaging the WAR..."
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Build completed. WAR generated in target/"

artifacts:
  files:
    - target/*.war
  discard-paths: yes
