version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven..."
      - mvn --version
  pre_build:
    commands:
      - chmod +x scripts/install_dependencies.sh
      - echo "Cleaning previous builds..."
      - mvn clean
  build:
    commands:
      - echo "Building WAR file with Maven..."
      - mvn package -DskipTests
  post_build:
    commands:
    - echo "Preparing deployment artifact..."
    - mkdir -p deploy
    - cp target/myapp.war deploy/
    - cp appspec.yml deploy/
    - cp -r scripts deploy/
    - cd deploy
    - zip -r MyJavaApp.zip *
    - echo "Artifact ready: MyJavaApp.zip"

artifacts:
  files:
    - target/*.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no
